site_name: ""
site_url: ""

theme:
  name: material
  palette:
    scheme: default
  font:
    text: Manrope
    code: JetBrains Mono

nav:
  - "": index.md

extra_css:
  - styles/extra.css

markdown_extensions:
  - attr_list
  - md_in_html