site_name: ""
site_url: ""

theme:
  name: material
  features: []
  palette:
    scheme: default

nav:
  - Home: index.md

extra_css:
  - styles/extra.css

markdown_extensions:
  - attr_list
  - md_in_html