site_name: ""
site_url: ""

theme:
  name: material
  palette:
    scheme: default
  font:
    text: Manrope
    code: JetBrains Mono

nav:
  - "": index.md

extra_css:
  - styles/extra.css
  - styles/diagram.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/gsap@3.12.5/dist/gsap.min.js
  - js/animate.js

markdown_extensions:
  - attr_list
  - md_in_html